import { Router } from 'express';
import authRoute from './auth.routes';
import referralRoute from './referral.routes';
import reviewRoutes from './reviews.routes';
import marketRoute from './market.routes';
import categoryRoute from './category.routes';
import productRoute from './product.routes';
import shoppingListRoute from './shoppingList.routes';
import mealRoute from './meal.routes';
import orderRoute from './order.routes';
import agentRoute from './agent.routes';
import kycRoute from './kyc.routes';
import AdminRoutes from './admin.routes';
import chatRoute from './chat.routes';
import notificationRoutes from './notification.routes';
import pushRoute from './push.routes';
import alatPayRoute from './payment/alatpay.routes';
import paystackRoute from './payment/paystack.routes';
import webhookStatusRoute from './payment/webhook-status.routes';
import seederRoute from './admin/seeder.routes';
import homeRoute from './home.routes';
import userAddressRoute from './userAddress.routes';
import discountCampaignRoute from './discountCampaign.routes';
import systemSettingsRoute from './systemSettings.routes';
import testRoute from './test.routes';
import deliveryRoute from './delivery.routes';

const router = Router();

router.use('/auth', authRoute);
router.use('/markets', marketRoute);
router.use('/category', categoryRoute);
router.use('/product', productRoute);
router.use('/shopping-list', shoppingListRoute);
router.use('/meals', mealRoute);
router.use('/order', orderRoute);
router.use('/agent', agentRoute);
router.use('/kyc', kycRoute);
router.use('/review', reviewRoutes);
router.use('/referral', referralRoute);
router.use('/admin', AdminRoutes);
router.use('/chat', chatRoute);
router.use('/notifications', notificationRoutes);
router.use('/push', pushRoute);
router.use('/payment/alatpay', alatPayRoute);
router.use('/payment/paystack', paystackRoute);
router.use('/payment/webhook-status', webhookStatusRoute);
router.use('/seeder', seederRoute);
router.use('/home', homeRoute);
router.use('/user-addresses', userAddressRoute);
router.use('/discounts', discountCampaignRoute);
router.use('/system/settings', systemSettingsRoute);
router.use('/test', testRoute); // Test endpoints (no auth required)
router.use('/delivery', deliveryRoute);

export default router;
